name: pdf_flutter_example
description: Demonstrates how to use the pdf_flutter plugin.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^3.0.0
  pdf_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/pdf/
  uses-material-design: true