name: pdf_flutter
description: Displaying PDF from Network, File and assets easily like we display
  Image in Flutter Widget.
version: 0.0.1
homepage: https://github.com/UchqunShodmonov/pdf_flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  http: ^1.2.2
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.erluxman.pdf_flutter
        pluginClass: PdfFlutterPlugin
      ios:
        pluginClass: PdfFlutterPlugin
